# Supplementary Table 2: full-model compute cost

Load the packaged measurements, apply manuscript units, and save the table.

## Load

In [1]:
from pathlib import Path

from IPython.display import display

from CytoBridge.results.compute_cost import (
    format_full_model_compute_cost,
    load_full_model_compute_cost,
    write_full_model_compute_cost_tables,
)

results = load_full_model_compute_cost()
display(results.measurements)

,dataset,time_points_used_for_training,training_time_point_labels,observed_cells_or_spots,training_time_seconds,peak_host_memory_mib,peak_gpu_allocation_mib
0,admouse,3,"2.5, 5.7, 17.9 months",172092,696.454413,2446.660156,708.554199
1,arista,5,"2, 5, 10, 15, 20 DPI",46199,1324.537501,9262.132812,870.358398
2,chicken_heart,4,"D4, D7, D10, D14",3550,761.157402,2833.042969,1922.019043
3,mosta,4,"E12.5, E13.5, E14.5, E15.5",344603,1997.504037,17023.750000,1051.018066
4,zebrafish,5,"5.25, 10, 12, 18, 24 hpf",11999,1239.225866,2174.132812,577.808594

## Format

Convert seconds to minutes and MiB to GiB.

In [2]:
table = format_full_model_compute_cost(results)
display(table)

,Dataset,Time points used for training,Observed cells/spots,Training time (min),Peak host memory (GiB),Peak GPU allocation (GiB)
0,AD mouse,"3: 2.5, 5.7, 17.9 months","172,092",11.6,2.39,0.69
1,ARISTA,"5: 2, 5, 10, 15, 20 DPI","46,199",22.1,9.05,0.85
2,Chicken heart,"4: D4, D7, D10, D14","3,550",12.7,2.77,1.88
3,MOSTA,"4: E12.5, E13.5, E14.5, E15.5","344,603",33.3,16.62,1.03
4,Zebrafish,"5: 5.25, 10, 12, 18, 24 hpf","11,999",20.7,2.12,0.56

## Save and check

In [3]:
output_dir = Path("outputs") / "full_model_compute_cost_notebook"
paths = write_full_model_compute_cost_tables(results, output_dir)
{name: {"file": path.name, "written": path.is_file()} for name, path in paths.items()}

{'raw': {'file': 'full_model_compute_cost.csv', 'written': True},
 'display': {'file': 'full_model_compute_cost_table.csv', 'written': True},
 'markdown': {'file': 'full_model_compute_cost_table.md', 'written': True}}

The same calculation is available from the command line:

```bash
python scripts/results/build_full_model_compute_cost_table.py --output-dir outputs/full_model_compute_cost
```