# Supplementary Table 2: full-model compute cost

Read the timing and memory measurements from the five training runs, convert the units used in the paper, and write the table.

## Reproduce this figure

Run the steps from top to bottom. Each step shows what it reads, what it writes,
and where to continue.

Replace text inside angle brackets with your path or value. For example,
`<output-dir>` means the directory where you want the files to be written.

### 1. measure each manuscript full-model run (Supplementary Table 2)

```text
cytobridge workflow --config <dataset> --step preprocess --step train --train --input-h5ad <raw.h5ad> --output-dir <run> --device cuda:0
```

Start with: `one manuscript model configuration and aligned H5AD per dataset`

Writes: `training_run_summary.json with elapsed seconds, peak host RSS and peak PyTorch allocation`

Next: `collect five rows`

### 2. collect and validate (Supplementary Table 2)

```text
python -m scripts.results.build_full_model_compute_cost_table --results-dir <compute-cost-results> --output-dir <formatted-table-run>
```

Start with: `five manuscript training_run_summary.json files`

Writes: `full_model_compute_cost.csv and a table of the collected source values`

Next: `format table`

### 3. format the table (Supplementary Table 2)

```text
python scripts/execute_paper_notebooks.py --notebook compute_cost --output-dir <notebook-run>
```

Start with: `full_model_compute_cost.csv`

Writes: `full_model_compute_cost_formatted.csv/.md`

Next: `copy values to the TeX-native table`

## Load figure inputs

In [1]:
import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)

from pathlib import Path

from IPython.display import display

from CytoBridge.results.compute_cost import (
    format_full_model_compute_cost,
    load_full_model_compute_cost,
    write_full_model_compute_cost_tables,
)

results = load_full_model_compute_cost()
display(results.measurements)

,dataset,time_points_used_for_training,training_time_point_labels,observed_cells_or_spots,training_time_seconds,peak_host_memory_mib,peak_gpu_allocation_mib
0,admouse,3,"2.5, 5.7, 17.9 months",172092,696.454413,2446.660156,708.554199
1,arista,5,"2, 5, 10, 15, 20 DPI",46199,1324.537501,9262.132812,870.358398
2,chicken_heart,4,"D4, D7, D10, D14",3550,761.157402,2833.042969,1922.019043
3,mosta,4,"E12.5, E13.5, E14.5, E15.5",344603,1997.504037,17023.750000,1051.018066
4,zebrafish,5,"5.25, 10, 12, 18, 24 hpf",11999,1239.225866,2174.132812,577.808594

## Format

Convert seconds to minutes and MiB to GiB.

In [2]:
table = format_full_model_compute_cost(results)
display(table)

,Dataset,Time points used for training,Observed cells/spots,Training time (min),Peak host memory (GiB),Peak GPU allocation (GiB)
0,AD mouse,"3: 2.5, 5.7, 17.9 months","172,092",11.6,2.39,0.69
1,ARISTA,"5: 2, 5, 10, 15, 20 DPI","46,199",22.1,9.05,0.85
2,Chicken heart,"4: D4, D7, D10, D14","3,550",12.7,2.77,1.88
3,MOSTA,"4: E12.5, E13.5, E14.5, E15.5","344,603",33.3,16.62,1.03
4,Zebrafish,"5: 5.25, 10, 12, 18, 24 hpf","11,999",20.7,2.12,0.56

## Save and check

In [3]:
output_dir = Path("outputs") / "full_model_compute_cost_notebook"
paths = write_full_model_compute_cost_tables(results, output_dir)
{name: {"file": path.name, "written": path.is_file()} for name, path in paths.items()}

{'raw': {'file': 'full_model_compute_cost.csv', 'written': True},
 'display': {'file': 'full_model_compute_cost_table.csv', 'written': True},
 'markdown': {'file': 'full_model_compute_cost_table.md', 'written': True}}

The same calculation is available from the command line:

```bash
python scripts/results/build_full_model_compute_cost_table.py --output-dir outputs/full_model_compute_cost
```